### ISSUE TITLE
How did you implement the scroll to zoom?

### ISSUE THREAD

**Issue by moshen** [attackgoat/noise_gui#1]
I've been toying with `egui-snarl` and I can't seem to find this in your code anywhere. Any help would be greatly appreciated.

**Comment by attackgoat** [comment]
I think this is handled by the `egui_snarl::Snarl<T>::show()` function - but this is a really old version of `egui_snarl` and I haven't made any updates, so this might be handled differently in current versions.

**Comment by moshen** [comment]
Ah I see now. It was changed:

https://github.com/zakarumych/egui-snarl/commit/55725607b394664b6743230bc670a5d695ee2f14#diff-ecec88c33adb7591ee6aa88e29b62ad52ef443611cba5e0f0ecac9b5725afdba

Probably should have looked more closely at `egui-snarl`. Thank you!

**Comment by attackgoat** [comment]
You beat me too it - I just figured out the same thing by rolling this repo forward and finding that Zooming doesn't work on the latest without command/control.
